### ISSUE TITLE
Webcron on shared hosting

### ISSUE THREAD

**Issue by Jolopu** [JeroenED/Webcron#4] opened 2021-02-22 22:55 UTC
Hi Jeroen,

can I run  Webcron on shared hosting? I have ssh access, FTP and phpMyAdmin. Do I need to install any dependencies? 

Thanks
- Jolopu

**Comment by JeroenED** [comment] 2021-02-23 06:35
Hi Jolopu, if you have ssh access and you can edit the crontab file (`$ crontab -e`) it should work flawlessly. Otherwise try with some free online cron service that you point each minute to https://(webcron-url)/webcron.php but I never really tested this.

**Comment by Jolopu** [comment] 2021-02-24 15:44
Hi Jeroen!
Thanks for your reply. My hosting provider limits the cronjob to one every 10 minutes. But I need to run it every single minute for sending my newsletter. So basically I need to get around the limitations of my hosting provider without using an external cron service. Could this be done with your tool?
Thanks!
-Jolopu

**Comment by JeroenED** [comment] 2021-02-24 15:53
Hi,

My tool won't help with this of you don't want to call it externally. I am thinking about rewriting the webcron.php to a sort of unix daemon. This would resolve your issue and also enable users to run per second instead of per minute, but this is not a priority atm.

Met vriendelijke groet,

----
Jeroen De Meerleer - Heirweg 5/G - 9870 Olsene - https://www.jeroened.be

Mijn excuses smartphones kunnen mails sturen

-------- Oorspronkelijk bericht --------
Aan 24 feb. 2021 16:44, Jolopu schreef:

**Comment by Jolopu** [comment] 2021-02-24 16:55
Thanks for the info. I look forward to the update of your tool.

**Comment by JeroenED** [comment] 2021-04-06 19:19
Since this issue eventually has the same solution as #1 I'm marking this issue as duplicate of it.

**Closed by JeroenED** 2021-04-06 19:19 UTC
